"""
daily_sports_scan.py
Morning edge report — scans MLB, NBA, NHL, NFL for today's top opportunities.

Designed to run daily at 8:00 AM PST via scheduler or cron. Scans all four
major sports, ranks by edge, and saves a timestamped markdown report to:
    reports/Sports/daily_edge_reports/YYYY-MM-DD_morning_scan.md

Usage:
    # Run manually
    python scripts/schedulers/daily_sports_scan.py

    # Run via APScheduler (8 AM PST daily)
    python scripts/schedulers/daily_sports_scan.py --daemon

    # Custom top N and output
    python scripts/schedulers/daily_sports_scan.py --top 50
"""

import os
import sys
import argparse
import logging
from datetime import datetime, timezone, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "shared"))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "kalshi"))
import paths  # noqa: F401
from config import DRY_RUN, MIN_EDGE_THRESHOLD
from logging_setup import setup_logging
from opportunity import Opportunity

from kalshi_client import KalshiClient
from edge_detector import scan_all_markets

log = setup_logging("daily_sports_scan")

# ── Configuration ────────────────────────────────────────────────────────────

SPORTS_FILTERS = ["nba", "nhl", "mlb", "nfl"]
REPORT_DIR = paths.PROJECT_ROOT / "reports" / "Sports" / "daily_edge_reports"
DEFAULT_TOP = 25


# ── Scanner ──────────────────────────────────────────────────────────────────

def scan_all_sports(client: KalshiClient, top_n: int = DEFAULT_TOP,
                    min_edge: float = MIN_EDGE_THRESHOLD) -> list[Opportunity]:
    """Scan all four major sports and return combined opportunities sorted by edge."""
    all_opps: list[Opportunity] = []

    for sport in SPORTS_FILTERS:
        log.info(f"Scanning {sport.upper()}...")
        try:
            opps = scan_all_markets(
                client=client,
                ticker_filter=sport,
                min_edge=min_edge,
                top_n=100,  # get plenty per sport, we'll trim after combining
            )
            log.info(f"  {sport.upper()}: {len(opps)} opportunities")
            all_opps.extend(opps)
        except Exception as e:
            log.error(f"  {sport.upper()} scan failed: {e}")

    # Sort by edge descending and take top N
    all_opps.sort(key=lambda o: o.edge, reverse=True)
    return all_opps[:top_n]


# ── Report Generation ────────────────────────────────────────────────────────

def generate_report(opportunities: list[Opportunity]) -> str:
    """Generate a markdown report from the scan results."""
    pst = timezone(timedelta(hours=-7))
    now = datetime.now(pst)
    lines = []

    lines.append(f"# Edge-Radar Daily Morning Scan")
    lines.append("")
    lines.append(f"**{now.strftime('%A, %B %d, %Y')}** | {now.strftime('%I:%M %p PST')}")
    lines.append("")
    lines.append(f"Sports: **{', '.join(s.upper() for s in SPORTS_FILTERS)}** | "
                 f"Top **{len(opportunities)}** opportunities by edge | "
                 f"Min edge: {MIN_EDGE_THRESHOLD:.0%}")
    lines.append("")

    if not opportunities:
        lines.append("> No opportunities found above edge threshold.")
        return "\n".join(lines)

    # Summary by category
    lines.append("## Summary")
    lines.append("")
    sport_counts: dict[str, int] = {}
    for o in opportunities:
        sport_counts[o.category] = sport_counts.get(o.category, 0) + 1

    lines.append("| Category | Count |")
    lines.append("|:---------|------:|")
    for cat, count in sorted(sport_counts.items(), key=lambda x: -x[1]):
        lines.append(f"| {cat} | {count} |")
    lines.append("")

    # Opportunity table
    lines.append("## Opportunities")
    lines.append("")
    lines.append("| # | Edge | Fair | Mkt | Conf | Side | Bet | Signals |")
    lines.append("|--:|-----:|-----:|----:|:-----|:-----|:----|:--------|")

    for i, o in enumerate(opportunities, 1):
        conf = o.confidence[:3].upper()
        side = o.side.upper()

        # Build signals column
        details = o.details or {}
        signals = []
        if details.get("team_stats", {}).get("stats_found"):
            ts = details["team_stats"]
            signals.append(f"{ts['team_record']} ({ts['signal']})")
        if details.get("sharp_money", {}).get("signal_found"):
            sm = details["sharp_money"]
            signals.append(f"sharp: {sm['sharp_side']}")
        if details.get("weather", {}).get("scoring_impact", {}).get("severity") not in (None, "none"):
            wi = details["weather"]["scoring_impact"]
            signals.append(f"weather: {wi['reason']}")

        signals_str = ", ".join(signals) if signals else ""

        lines.append(
            f"| {i} | {o.edge:+.1%} | {o.fair_value:.2f} | {o.market_price:.2f} | "
            f"{conf} | {side} | {o.title} | {signals_str} |"
        )

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(f"*Generated by Edge-Radar | {now.strftime('%Y-%m-%d %H:%M PST')} | DRY_RUN={DRY_RUN}*")

    return "\n".join(lines)


def save_report(report: str) -> Path:
    """Save report to the daily reports directory with today's date."""
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    pst = timezone(timedelta(hours=-7))
    today = datetime.now(pst).strftime("%Y-%m-%d")
    report_path = REPORT_DIR / f"{today}_morning_scan.md"

    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report + "\n")

    log.info(f"Report saved to: {report_path}")
    return report_path


# ── Daemon Mode ──────────────────────────────────────────────────────────────

def run_scan(top_n: int = DEFAULT_TOP):
    """Run the scan, generate report, print and save."""
    log.info("Starting daily morning scan...")

    client = KalshiClient()
    opportunities = scan_all_sports(client, top_n=top_n)

    report = generate_report(opportunities)
    print(report)

    path = save_report(report)
    log.info(f"Scan complete. {len(opportunities)} opportunities. Report: {path}")


def run_daemon():
    """Run as a daemon — executes scan at 8:00 AM PST daily."""
    from apscheduler.schedulers.blocking import BlockingScheduler
    from apscheduler.triggers.cron import CronTrigger

    log.info("Starting daily scan daemon (8:00 AM PST)...")

    scheduler = BlockingScheduler()

    # 8:00 AM PST = 15:00 UTC (or 16:00 UTC during DST)
    # Using America/Los_Angeles timezone for automatic DST handling
    scheduler.add_job(
        run_scan,
        CronTrigger(hour=8, minute=0, timezone="America/Los_Angeles"),
        id="daily_morning_scan",
        replace_existing=True,
    )

    # Also run once immediately on startup
    run_scan()

    log.info("Daemon running. Next scan at 8:00 AM PST. Ctrl+C to stop.")

    try:
        scheduler.start()
    except (KeyboardInterrupt, SystemExit):
        log.info("Daemon stopped.")


# ── CLI ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Daily morning edge scan — MLB, NBA, NHL, NFL"
    )
    parser.add_argument(
        "--top", type=int, default=DEFAULT_TOP,
        help=f"Number of top opportunities to include (default: {DEFAULT_TOP})"
    )
    parser.add_argument(
        "--daemon", action="store_true",
        help="Run as daemon — scans at 8:00 AM PST daily"
    )

    args = parser.parse_args()

    if args.daemon:
        run_daemon()
    else:
        run_scan(top_n=args.top)


if __name__ == "__main__":
    main()
